# Generated by Django 4.1.5 on 2023-02-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_author', 'Author Editing'), ('can_delete_author', 'Author Deleting'), ('can_create_author', 'Author Creating'))},
        ),
    ]
