# Generated by Django 4.1.5 on 2023-02-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_update_author', 'Author Updating'), ('can_delete_author', 'Author Deleting'), ('can_create_author', 'Author Creating'))},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_update_book', 'Book Updating'), ('can_delete_book', 'Book Deleting'), ('can_create_book', 'Book Creating'))},
        ),
    ]
